### ISSUE TITLE
As an engineer, I want to have a well-seeded database so that I am able to seed hundreds of products with dummy data so that a “pagination” feature could be implemented in the future.

### ISSUE THREAD

**Issue by dianalduran** [grace-shopper-team-1/Grace-Grocer#7]
- [x] #6 Write product model
- [x] #12 finish users model
- [x] modify grocery names #29 
- [x] change grocery price to pennies #46
